# Generated by Django 4.1.1 on 2022-09-14 19:12

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('App_PWD_Management', '0002_userpassword'),
    ]

    operations = [
        migrations.RenameField(
            model_name='userpassword',
            old_name='pwd',
            new_name='passwords',
        ),
    ]
