# Generated by Django 4.1.1 on 2022-09-14 19:28

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('App_PWD_Management', '0004_rename_passwords_userpassword_password'),
    ]

    operations = [
        migrations.RenameField(
            model_name='userpassword',
            old_name='cust',
            new_name='email',
        ),
        migrations.RenameField(
            model_name='userpassword',
            old_name='password',
            new_name='passwords',
        ),
    ]
