# Generated by Django 4.1.1 on 2022-09-14 19:32

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('App_PWD_Management', '0005_rename_cust_userpassword_email_and_more'),
    ]

    operations = [
        migrations.RenameField(
            model_name='userpassword',
            old_name='passwords',
            new_name='password',
        ),
    ]
